# Generated by Django 5.2.3 on 2025-06-18 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('quantity', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('pickup_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('expired', 'Expired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('donor', 'Food Donor'), ('recipient', 'Food Recipient'), ('admin', 'Administrator')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('needs_description', models.TextField(blank=True, null=True)),
                ('default_quantity_unit', models.CharField(choices=[('Kilograms (kg)', 'Kilograms (kg)'), ('Grams (g)', 'Grams (g)'), ('Liters (L)', 'Liters (L)'), ('Units', 'Units')], default='Units', max_length=50)),
                ('preferred_pickup_time', models.CharField(blank=True, choices=[('Morning (8am–12pm)', 'Morning (8am–12pm)'), ('Afternoon (12pm–4pm)', 'Afternoon (12pm–4pm)'), ('Evening (4pm–8pm)', 'Evening (4pm–8pm)')], max_length=50, null=True)),
                ('advance_notice', models.IntegerField(blank=True, choices=[(1, '1 day'), (2, '2 days'), (3, '3 days'), (7, '1 week')], default=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity_amount', models.FloatField(default=1.0)),
                ('quantity_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('pieces', 'Pieces'), ('portions', 'Portions'), ('litres', 'Litres'), ('packs', 'Packs')], default='kg', max_length=10)),
                ('category', models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains & Cereals'), ('dairy', 'Dairy Products'), ('meat', 'Meat & Poultry'), ('seafood', 'Seafood'), ('bakery', 'Bakery Items'), ('prepared', 'Prepared Food'), ('beverages', 'Beverages'), ('canned', 'Canned Goods'), ('others', 'Other')], max_length=100)),
                ('dietary_info', models.TextField(blank=True, null=True)),
                ('known_allergens', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('delivered', 'Delivered'), ('expired', 'Expired')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='fooddonor.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(default='General', max_length=50)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooddonor.fooddonation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooddonor.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
