# Generated by Django 5.2 on 2025-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
