# Generated by Django 5.2 on 2025-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0003_alter_donationrequest_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
