# Generated by Django 5.1.5 on 2025-06-12 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0004_donationrequest_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('pickup_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('expired', 'Expired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
