# Generated by Django 5.2 on 2025-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0007_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_images/'),
        ),
    ]
