# Generated by Django 5.2 on 2025-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0008_fooddonation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
