# Generated by Django 5.2 on 2025-06-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0009_alter_fooddonation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_quantity_unit',
            field=models.CharField(choices=[('Kilograms (kg)', 'Kilograms (kg)'), ('Grams (g)', 'Grams (g)'), ('Liters (L)', 'Liters (L)'), ('Units', 'Units')], default='Units', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
