# Generated by Django 5.2 on 2025-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0010_profile_default_quantity_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_pickup_time',
            field=models.CharField(blank=True, choices=[('Morning (8am–12pm)', 'Morning (8am–12pm)'), ('Afternoon (12pm–4pm)', 'Afternoon (12pm–4pm)'), ('Evening (4pm–8pm)', 'Evening (4pm–8pm)')], max_length=50, null=True),
        ),
    ]
