# Generated by Django 5.2 on 2025-06-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0011_profile_preferred_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='advance_notice',
            field=models.IntegerField(blank=True, choices=[(1, '1 day'), (2, '2 days'), (3, '3 days'), (7, '1 week')], default=1, null=True),
        ),
    ]
