# Generated by Django 5.2 on 2025-06-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0012_profile_advance_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('grains', 'Grains'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='dietary_info',
            field=models.CharField(choices=[('halal', 'Halal'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten-Free'), ('none', 'None')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='known_allergens',
            field=models.CharField(blank=True, help_text='Comma-separated list or tags', max_length=100),
        ),
    ]
