# Generated by Django 5.2 on 2025-06-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0013_fooddonation_category_fooddonation_dietary_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains & Cereals'), ('dairy', 'Dairy Products'), ('meat', 'Meat & Poultry'), ('seafood', 'Seafood'), ('bakery', 'Bakery Items'), ('prepared', 'Prepared Food'), ('beverages', 'Beverages'), ('canned', 'Canned Goods'), ('others', 'Other')], default='others', max_length=50),
        ),
    ]
