# Generated by Django 5.2 on 2025-06-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0014_alter_fooddonation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains & Cereals'), ('dairy', 'Dairy Products'), ('meat', 'Meat & Poultry'), ('seafood', 'Seafood'), ('bakery', 'Bakery Items'), ('prepared', 'Prepared Food'), ('beverages', 'Beverages'), ('canned', 'Canned Goods'), ('others', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='dietary_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='known_allergens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
