# Generated by Django 5.2 on 2025-06-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0015_alter_fooddonation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='quantity_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('pieces', 'Pieces'), ('portions', 'Portions'), ('litres', 'Litres'), ('packs', 'Packs')], default='kg', max_length=10),
        ),
    ]
