# Generated by Django 5.2 on 2025-06-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0016_remove_fooddonation_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='quantity_amount',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='quantity_unit',
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='quantity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
