# Generated by Django 5.2 on 2025-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonor', '0017_remove_fooddonation_quantity_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='quantity_amount',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('pieces', 'Pieces'), ('portions', 'Portions'), ('litres', 'Litres'), ('packs', 'Packs')], default='kg', max_length=10),
        ),
    ]
