# Generated by Django 5.1.5 on 2025-04-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fooddonor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_food_types', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('preferred_pickup_times', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient', models.OneToOneField(limit_choices_to={'role': 'recipient'}, on_delete=django.db.models.deletion.CASCADE, to='fooddonor.profile')),
            ],
        ),
    ]
