# Generated by Django 5.2 on 2025-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0003_recipientprofile_delete_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientprofile',
            name='role',
            field=models.CharField(default='recipient', max_length=20),
        ),
    ]
